### PR TITLE
Create russian lang

### PR DESCRIPTION
**Pull request by Heimdallr-1**
Full translation of the book. TIA

### CODE REVIEW

**Comment by XxRexRaptorxX** [comment]
Thanks for your translation, i would give you the Translator-Rank on my discord for your efforts if you like :) 

> https://discord.gg/ycRJJk8EXV

**Comment by Heimdallr-1** [comment]
Thanks, gladly!

**Comment by XxRexRaptorxX** [comment]
What is your discord name? DrHesperus?

**Comment by Heimdallr-1** [comment]
No, I haven't joined the Discord server yet. I don't have time right now, but I'll join tomorrow with the same username.

**Pull request merged**
